services:
  mysql:
    image: mysql:8.0
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: root1234
      MYSQL_DATABASE: shopdevgo
      MYSQL_USER: root
      MYSQL_PASSWORD: root1234
    ports:
      - "33306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3
  redis:
    image: redis:7.0
    container_name: redis_container
    ports:
      - "6381:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_container
    environment:
      PMA_HOST: mysql_container
      MYSQL_ROOT_PASSWORD: root1234
    ports:
      - "8080:80"
  # crm.shopdevgo.com:
  #   container_name: go_backend_crm_shopdev
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   depends_on:
  #     mysql:
  #       condition: service_healthy
  #     redis:
  #       condition: service_healthy
  #   ports:
  #     - "8004:8002"

volumes:
  mysql_data:
  redis_data: